import { PrismaClient, Prisma } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL is not set");

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

// ─── Care level score profiles ────────────────────────────────────────────────
const SCORE_PROFILES: Record<
  number,
  { k1: number; k2: number; k3: number; k4: number }
> = {
  1: { k1: 21, k2: 45, k3: 26, k4: 26 },
  2: { k1: 17, k2: 37, k3: 21, k4: 22 },
  3: { k1: 13, k2: 29, k3: 16, k4: 17 },
  4: { k1: 10, k2: 21, k3: 11, k4: 13 },
  5: { k1: 7, k2: 13, k3: 7, k4: 9 },
  6: { k1: 4, k2: 7, k3: 3, k4: 5 },
  7: { k1: 1, k2: 2, k3: 1, k4: 2 },
};

// ─── Seniors data (100 seniors in Rzeszów area) ───────────────────────────────
type Gender = "K" | "M";
type IdConf = "NAME_DOB" | "NAME_DOB_EXTRA" | "STAFF_CONFIRMED" | "NEW_RECORD";

interface SeniorData {
  id: string;
  firstName: string;
  lastName: string;
  dateOfBirth: Date;
  gender: Gender;
  address: string;
  city: string;
  postalCode: string;
  phone: string;
  identificationConfidence: IdConf;
  geoLat: number;
  geoLon: number;
  careLevel: number;
}

const SENIORS: SeniorData[] = [
  // ── Rzeszów Śródmieście & centrum ─────────────────────────────────────────
  {
    id: "s-001",
    firstName: "Janina",
    lastName: "Kowalska",
    dateOfBirth: new Date("1945-03-15"),
    gender: "K",
    address: "ul. Rejtana 12",
    city: "Rzeszów",
    postalCode: "35-310",
    phone: "501 234 501",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.04,
    geoLon: 21.999,
    careLevel: 1,
  },
  {
    id: "s-002",
    firstName: "Stanislaw",
    lastName: "Nowak",
    dateOfBirth: new Date("1938-07-22"),
    gender: "M",
    address: "ul. Slowackiego 5",
    city: "Rzeszów",
    postalCode: "35-060",
    phone: "502 234 502",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0418,
    geoLon: 22.0012,
    careLevel: 2,
  },
  {
    id: "s-003",
    firstName: "Maria",
    lastName: "Wisniewska",
    dateOfBirth: new Date("1950-11-08"),
    gender: "K",
    address: "ul. Kopernika 7",
    city: "Rzeszów",
    postalCode: "35-001",
    phone: "503 234 503",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0392,
    geoLon: 22.0035,
    careLevel: 3,
  },
  {
    id: "s-004",
    firstName: "Tadeusz",
    lastName: "Wojcik",
    dateOfBirth: new Date("1942-01-30"),
    gender: "M",
    address: "ul. Krasickiego 3",
    city: "Rzeszów",
    postalCode: "35-055",
    phone: "504 234 504",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0445,
    geoLon: 21.9978,
    careLevel: 4,
  },
  {
    id: "s-005",
    firstName: "Zofia",
    lastName: "Kaminska",
    dateOfBirth: new Date("1936-09-14"),
    gender: "K",
    address: "ul. 3 Maja 18",
    city: "Rzeszów",
    postalCode: "35-030",
    phone: "505 234 505",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0421,
    geoLon: 22.0056,
    careLevel: 5,
  },
  {
    id: "s-006",
    firstName: "Helena",
    lastName: "Mazur",
    dateOfBirth: new Date("1941-06-02"),
    gender: "K",
    address: "ul. Targowa 22",
    city: "Rzeszów",
    postalCode: "35-064",
    phone: "506 234 506",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0408,
    geoLon: 22.0078,
    careLevel: 6,
  },
  {
    id: "s-007",
    firstName: "Jan",
    lastName: "Lewandowski",
    dateOfBirth: new Date("1935-12-19"),
    gender: "M",
    address: "ul. Krakowska 44",
    city: "Rzeszów",
    postalCode: "35-060",
    phone: "507 234 507",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0382,
    geoLon: 21.9965,
    careLevel: 7,
  },
  {
    id: "s-008",
    firstName: "Anna",
    lastName: "Krawczyk",
    dateOfBirth: new Date("1948-04-11"),
    gender: "K",
    address: "ul. Mickiewicza 8",
    city: "Rzeszów",
    postalCode: "35-001",
    phone: "508 234 508",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0435,
    geoLon: 22.0023,
    careLevel: 1,
  },
  {
    id: "s-009",
    firstName: "Jozef",
    lastName: "Dabrowski",
    dateOfBirth: new Date("1940-08-25"),
    gender: "M",
    address: "ul. Pilsudskiego 15",
    city: "Rzeszów",
    postalCode: "35-001",
    phone: "509 234 509",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0415,
    geoLon: 22.0048,
    careLevel: 2,
  },
  {
    id: "s-010",
    firstName: "Barbara",
    lastName: "Szymanska",
    dateOfBirth: new Date("1944-02-14"),
    gender: "K",
    address: "ul. Grunwaldzka 6",
    city: "Rzeszów",
    postalCode: "35-068",
    phone: "510 234 510",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0388,
    geoLon: 22.0015,
    careLevel: 3,
  },
  // ── Rzeszów Nowe Miasto / Północ ──────────────────────────────────────────
  {
    id: "s-011",
    firstName: "Edward",
    lastName: "Zielinski",
    dateOfBirth: new Date("1937-10-07"),
    gender: "M",
    address: "ul. Hetmanska 10",
    city: "Rzeszów",
    postalCode: "35-045",
    phone: "511 234 511",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.053,
    geoLon: 22.0045,
    careLevel: 4,
  },
  {
    id: "s-012",
    firstName: "Wanda",
    lastName: "Piotrowska",
    dateOfBirth: new Date("1952-07-19"),
    gender: "K",
    address: "ul. Dabrowskiego 3",
    city: "Rzeszów",
    postalCode: "35-044",
    phone: "512 234 512",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0552,
    geoLon: 22.0062,
    careLevel: 5,
  },
  {
    id: "s-013",
    firstName: "Henryk",
    lastName: "Kozlowski",
    dateOfBirth: new Date("1943-05-28"),
    gender: "M",
    address: "ul. Wyspiańskiego 17",
    city: "Rzeszów",
    postalCode: "35-111",
    phone: "513 234 513",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0568,
    geoLon: 22.0018,
    careLevel: 6,
  },
  {
    id: "s-014",
    firstName: "Irena",
    lastName: "Grabowska",
    dateOfBirth: new Date("1939-03-04"),
    gender: "K",
    address: "ul. Podkarpacka 21",
    city: "Rzeszów",
    postalCode: "35-082",
    phone: "514 234 514",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0511,
    geoLon: 22.0033,
    careLevel: 7,
  },
  {
    id: "s-015",
    firstName: "Zbigniew",
    lastName: "Nowakowski",
    dateOfBirth: new Date("1946-12-30"),
    gender: "M",
    address: "ul. Lwowska 5",
    city: "Rzeszów",
    postalCode: "35-301",
    phone: "515 234 515",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.049,
    geoLon: 22.0071,
    careLevel: 7,
  },
  {
    id: "s-016",
    firstName: "Krystyna",
    lastName: "Jankowska",
    dateOfBirth: new Date("1955-09-16"),
    gender: "K",
    address: "ul. Konopnickiej 14",
    city: "Rzeszów",
    postalCode: "35-211",
    phone: "516 234 516",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0543,
    geoLon: 22.0089,
    careLevel: 4,
  },
  {
    id: "s-017",
    firstName: "Marian",
    lastName: "Wozniak",
    dateOfBirth: new Date("1933-06-08"),
    gender: "M",
    address: "ul. Orzeszkowej 9",
    city: "Rzeszów",
    postalCode: "35-114",
    phone: "517 234 517",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0576,
    geoLon: 22.0056,
    careLevel: 5,
  },
  {
    id: "s-018",
    firstName: "Danuta",
    lastName: "Kwiatkowska",
    dateOfBirth: new Date("1949-01-22"),
    gender: "K",
    address: "ul. Jana Pawla II 31",
    city: "Rzeszów",
    postalCode: "35-317",
    phone: "518 234 518",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0521,
    geoLon: 22.0012,
    careLevel: 3,
  },
  {
    id: "s-019",
    firstName: "Ryszard",
    lastName: "Pawlowski",
    dateOfBirth: new Date("1941-11-15"),
    gender: "M",
    address: "ul. Matejki 2",
    city: "Rzeszów",
    postalCode: "35-064",
    phone: "519 234 519",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0498,
    geoLon: 22.0098,
    careLevel: 6,
  },
  {
    id: "s-020",
    firstName: "Halina",
    lastName: "Michalska",
    dateOfBirth: new Date("1953-08-03"),
    gender: "K",
    address: "ul. Prusa 7",
    city: "Rzeszów",
    postalCode: "35-074",
    phone: "520 234 520",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0559,
    geoLon: 21.9997,
    careLevel: 2,
  },
  // ── Rzeszów Południe / Słocina / Zwięczyca ────────────────────────────────
  {
    id: "s-021",
    firstName: "Franciszek",
    lastName: "Adamski",
    dateOfBirth: new Date("1938-04-20"),
    gender: "M",
    address: "ul. Sienkiewicza 11",
    city: "Rzeszów",
    postalCode: "35-075",
    phone: "521 234 521",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0298,
    geoLon: 21.9945,
    careLevel: 4,
  },
  {
    id: "s-022",
    firstName: "Teresa",
    lastName: "Dudek",
    dateOfBirth: new Date("1947-07-13"),
    gender: "K",
    address: "ul. Armii Krajowej 26",
    city: "Rzeszów",
    postalCode: "35-307",
    phone: "522 234 522",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0271,
    geoLon: 21.9968,
    careLevel: 3,
  },
  {
    id: "s-023",
    firstName: "Kazimierz",
    lastName: "Wrobel",
    dateOfBirth: new Date("1942-09-29"),
    gender: "M",
    address: "ul. Niepodleglosci 4",
    city: "Rzeszów",
    postalCode: "35-303",
    phone: "523 234 523",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0312,
    geoLon: 21.9922,
    careLevel: 5,
  },
  {
    id: "s-024",
    firstName: "Jadwiga",
    lastName: "Jablonska",
    dateOfBirth: new Date("1934-02-17"),
    gender: "K",
    address: "ul. Olszowa 8",
    city: "Rzeszów",
    postalCode: "35-506",
    phone: "524 234 524",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0247,
    geoLon: 21.9978,
    careLevel: 6,
  },
  {
    id: "s-025",
    firstName: "Aleksander",
    lastName: "Malinowski",
    dateOfBirth: new Date("1936-05-30"),
    gender: "M",
    address: "ul. Drzewna 13",
    city: "Rzeszów",
    postalCode: "35-508",
    phone: "525 234 525",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.028,
    geoLon: 21.9903,
    careLevel: 7,
  },
  {
    id: "s-026",
    firstName: "Stanisława",
    lastName: "Olszewska",
    dateOfBirth: new Date("1944-10-06"),
    gender: "K",
    address: "ul. Kwiatowa 16",
    city: "Rzeszów",
    postalCode: "35-505",
    phone: "526 234 526",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0336,
    geoLon: 21.9955,
    careLevel: 2,
  },
  {
    id: "s-027",
    firstName: "Eugeniusz",
    lastName: "Borkowski",
    dateOfBirth: new Date("1939-08-11"),
    gender: "M",
    address: "ul. Polna 9",
    city: "Rzeszów",
    postalCode: "35-509",
    phone: "527 234 527",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0319,
    geoLon: 22.0009,
    careLevel: 3,
  },
  {
    id: "s-028",
    firstName: "Genowefa",
    lastName: "Stepien",
    dateOfBirth: new Date("1951-12-25"),
    gender: "K",
    address: "ul. Leśna 5",
    city: "Rzeszów",
    postalCode: "35-507",
    phone: "528 234 528",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0261,
    geoLon: 22.0031,
    careLevel: 4,
  },
  {
    id: "s-029",
    firstName: "Waldemar",
    lastName: "Grabowski",
    dateOfBirth: new Date("1945-07-18"),
    gender: "M",
    address: "ul. Zielona 20",
    city: "Rzeszów",
    postalCode: "35-510",
    phone: "529 234 529",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0344,
    geoLon: 21.9989,
    careLevel: 5,
  },
  {
    id: "s-030",
    firstName: "Leokadia",
    lastName: "Zak",
    dateOfBirth: new Date("1932-03-09"),
    gender: "K",
    address: "ul. Rzeczna 3",
    city: "Rzeszów",
    postalCode: "35-511",
    phone: "530 234 530",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0298,
    geoLon: 22.0054,
    careLevel: 6,
  },
  // ── Rzeszów Wschód / Staroniwa / Budziwój ────────────────────────────────
  {
    id: "s-031",
    firstName: "Wiesław",
    lastName: "Kaczmarek",
    dateOfBirth: new Date("1940-06-14"),
    gender: "M",
    address: "ul. Przemyska 7",
    city: "Rzeszów",
    postalCode: "35-234",
    phone: "531 234 531",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.039,
    geoLon: 22.022,
    careLevel: 1,
  },
  {
    id: "s-032",
    firstName: "Cecylia",
    lastName: "Urbaniak",
    dateOfBirth: new Date("1946-11-28"),
    gender: "K",
    address: "ul. Wschodnia 12",
    city: "Rzeszów",
    postalCode: "35-350",
    phone: "532 234 532",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0371,
    geoLon: 22.0244,
    careLevel: 2,
  },
  {
    id: "s-033",
    firstName: "Roman",
    lastName: "Marciniak",
    dateOfBirth: new Date("1937-04-02"),
    gender: "M",
    address: "ul. Podleśna 4",
    city: "Rzeszów",
    postalCode: "35-366",
    phone: "533 234 533",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.035,
    geoLon: 22.0198,
    careLevel: 3,
  },
  {
    id: "s-034",
    firstName: "Władysława",
    lastName: "Krol",
    dateOfBirth: new Date("1943-09-21"),
    gender: "K",
    address: "ul. Słoneczna 15",
    city: "Rzeszów",
    postalCode: "35-234",
    phone: "534 234 534",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0409,
    geoLon: 22.0267,
    careLevel: 4,
  },
  {
    id: "s-035",
    firstName: "Bronisław",
    lastName: "Walczak",
    dateOfBirth: new Date("1931-01-17"),
    gender: "M",
    address: "ul. Różana 8",
    city: "Rzeszów",
    postalCode: "35-240",
    phone: "535 234 535",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0328,
    geoLon: 22.0289,
    careLevel: 5,
  },
  {
    id: "s-036",
    firstName: "Mieczysława",
    lastName: "Wysocka",
    dateOfBirth: new Date("1938-06-30"),
    gender: "K",
    address: "ul. Równa 22",
    city: "Rzeszów",
    postalCode: "35-245",
    phone: "536 234 536",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0245,
    geoLon: 22.0312,
    careLevel: 6,
  },
  {
    id: "s-037",
    firstName: "Leszek",
    lastName: "Szczepanski",
    dateOfBirth: new Date("1950-03-13"),
    gender: "M",
    address: "ul. Jasna 1",
    city: "Rzeszów",
    postalCode: "35-236",
    phone: "537 234 537",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0418,
    geoLon: 22.0311,
    careLevel: 3,
  },
  {
    id: "s-038",
    firstName: "Zuzanna",
    lastName: "Pietrzak",
    dateOfBirth: new Date("1942-08-07"),
    gender: "K",
    address: "ul. Nowa 6",
    city: "Rzeszów",
    postalCode: "35-255",
    phone: "538 234 538",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0378,
    geoLon: 22.0334,
    careLevel: 4,
  },
  {
    id: "s-039",
    firstName: "Andrzej",
    lastName: "Tomczak",
    dateOfBirth: new Date("1935-10-25"),
    gender: "M",
    address: "ul. Stara 11",
    city: "Rzeszów",
    postalCode: "35-258",
    phone: "539 234 539",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0356,
    geoLon: 22.0356,
    careLevel: 5,
  },
  {
    id: "s-040",
    firstName: "Elżbieta",
    lastName: "Pawlak",
    dateOfBirth: new Date("1948-05-19"),
    gender: "K",
    address: "ul. Dolna 3",
    city: "Rzeszów",
    postalCode: "35-260",
    phone: "540 234 540",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0289,
    geoLon: 22.0264,
    careLevel: 2,
  },
  // ── Rzeszów Zachód / Przybyszówka / Miłocin ───────────────────────────────
  {
    id: "s-041",
    firstName: "Czesław",
    lastName: "Kowal",
    dateOfBirth: new Date("1941-02-09"),
    gender: "M",
    address: "ul. Zachodnia 17",
    city: "Rzeszów",
    postalCode: "35-082",
    phone: "541 234 541",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0512,
    geoLon: 21.981,
    careLevel: 1,
  },
  {
    id: "s-042",
    firstName: "Kazimiera",
    lastName: "Wrona",
    dateOfBirth: new Date("1943-12-16"),
    gender: "K",
    address: "ul. Górna 9",
    city: "Rzeszów",
    postalCode: "35-083",
    phone: "542 234 542",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0534,
    geoLon: 21.9756,
    careLevel: 3,
  },
  {
    id: "s-043",
    firstName: "Bogdan",
    lastName: "Sobieraj",
    dateOfBirth: new Date("1936-07-05"),
    gender: "M",
    address: "ul. Centralna 14",
    city: "Rzeszów",
    postalCode: "35-085",
    phone: "543 234 543",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0489,
    geoLon: 21.9789,
    careLevel: 4,
  },
  {
    id: "s-044",
    firstName: "Rozalia",
    lastName: "Wojtas",
    dateOfBirth: new Date("1952-04-27"),
    gender: "K",
    address: "ul. Poprzeczna 2",
    city: "Rzeszów",
    postalCode: "35-086",
    phone: "544 234 544",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0456,
    geoLon: 21.9823,
    careLevel: 5,
  },
  {
    id: "s-045",
    firstName: "Mirosław",
    lastName: "Cieslak",
    dateOfBirth: new Date("1944-09-01"),
    gender: "M",
    address: "ul. Zacisze 7",
    city: "Rzeszów",
    postalCode: "35-088",
    phone: "545 234 545",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0567,
    geoLon: 21.9845,
    careLevel: 6,
  },
  {
    id: "s-046",
    firstName: "Władysław",
    lastName: "Ostrowski",
    dateOfBirth: new Date("1930-11-14"),
    gender: "M",
    address: "ul. Polna 22",
    city: "Rzeszów",
    postalCode: "35-089",
    phone: "546 234 546",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0601,
    geoLon: 21.9867,
    careLevel: 7,
  },
  {
    id: "s-047",
    firstName: "Wiesława",
    lastName: "Sikora",
    dateOfBirth: new Date("1955-01-31"),
    gender: "K",
    address: "ul. Miodowa 5",
    city: "Rzeszów",
    postalCode: "35-091",
    phone: "547 234 547",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0478,
    geoLon: 21.9801,
    careLevel: 4,
  },
  {
    id: "s-048",
    firstName: "Jerzy",
    lastName: "Kucharski",
    dateOfBirth: new Date("1948-06-22"),
    gender: "M",
    address: "ul. Piaskowa 11",
    city: "Rzeszów",
    postalCode: "35-093",
    phone: "548 234 548",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0523,
    geoLon: 21.9834,
    careLevel: 3,
  },
  {
    id: "s-049",
    firstName: "Henryka",
    lastName: "Bartoszewska",
    dateOfBirth: new Date("1937-03-08"),
    gender: "K",
    address: "ul. Wiśniowa 16",
    city: "Rzeszów",
    postalCode: "35-095",
    phone: "549 234 549",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0445,
    geoLon: 21.9867,
    careLevel: 2,
  },
  {
    id: "s-050",
    firstName: "Krzysztof",
    lastName: "Nowicki",
    dateOfBirth: new Date("1940-10-19"),
    gender: "M",
    address: "ul. Brzoskwiniowa 3",
    city: "Rzeszów",
    postalCode: "35-097",
    phone: "550 234 550",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.059,
    geoLon: 21.9778,
    careLevel: 5,
  },
  // ── Głogów Małopolski ─────────────────────────────────────────────────────
  {
    id: "s-051",
    firstName: "Anna",
    lastName: "Szewczyk",
    dateOfBirth: new Date("1942-01-14"),
    gender: "K",
    address: "ul. Rynek 4",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "551 234 551",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1623,
    geoLon: 22.0249,
    careLevel: 1,
  },
  {
    id: "s-052",
    firstName: "Stanisław",
    lastName: "Baran",
    dateOfBirth: new Date("1934-05-26"),
    gender: "M",
    address: "ul. Kościelna 8",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "552 234 552",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.1645,
    geoLon: 22.0198,
    careLevel: 2,
  },
  {
    id: "s-053",
    firstName: "Maria",
    lastName: "Lis",
    dateOfBirth: new Date("1947-08-09"),
    gender: "K",
    address: "ul. Parkowa 12",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "553 234 553",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.1601,
    geoLon: 22.0312,
    careLevel: 3,
  },
  {
    id: "s-054",
    firstName: "Józef",
    lastName: "Czajka",
    dateOfBirth: new Date("1939-11-03"),
    gender: "M",
    address: "ul. Leśna 6",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "554 234 554",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1667,
    geoLon: 22.0267,
    careLevel: 4,
  },
  {
    id: "s-055",
    firstName: "Helena",
    lastName: "Bąk",
    dateOfBirth: new Date("1936-04-17"),
    gender: "K",
    address: "ul. Słoneczna 3",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "555 234 555",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1589,
    geoLon: 22.0178,
    careLevel: 5,
  },
  {
    id: "s-056",
    firstName: "Tadeusz",
    lastName: "Kowalik",
    dateOfBirth: new Date("1933-09-21"),
    gender: "M",
    address: "ul. Ogrodowa 15",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "556 234 556",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.1634,
    geoLon: 22.0156,
    careLevel: 6,
  },
  {
    id: "s-057",
    firstName: "Irena",
    lastName: "Wysocka",
    dateOfBirth: new Date("1945-02-28"),
    gender: "K",
    address: "ul. Polna 7",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "557 234 557",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.1578,
    geoLon: 22.029,
    careLevel: 7,
  },
  {
    id: "s-058",
    firstName: "Zygmunt",
    lastName: "Kowalczyk",
    dateOfBirth: new Date("1940-07-12"),
    gender: "M",
    address: "ul. Różana 2",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "558 234 558",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1656,
    geoLon: 22.0134,
    careLevel: 4,
  },
  {
    id: "s-059",
    firstName: "Barbara",
    lastName: "Wilk",
    dateOfBirth: new Date("1948-12-06"),
    gender: "K",
    address: "ul. Nowa 9",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "559 234 559",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1612,
    geoLon: 22.0356,
    careLevel: 3,
  },
  {
    id: "s-060",
    firstName: "Janusz",
    lastName: "Duda",
    dateOfBirth: new Date("1951-06-30"),
    gender: "M",
    address: "ul. Stara 11",
    city: "Głogów Małopolski",
    postalCode: "36-060",
    phone: "560 234 560",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.1578,
    geoLon: 22.0089,
    careLevel: 2,
  },
  // ── Łańcut ───────────────────────────────────────────────────────────────
  {
    id: "s-061",
    firstName: "Zofia",
    lastName: "Zielinska",
    dateOfBirth: new Date("1941-03-18"),
    gender: "K",
    address: "ul. Zamkowa 4",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "561 234 561",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0678,
    geoLon: 22.2234,
    careLevel: 1,
  },
  {
    id: "s-062",
    firstName: "Ryszard",
    lastName: "Mazurek",
    dateOfBirth: new Date("1938-10-25"),
    gender: "M",
    address: "ul. Kosciuszki 11",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "562 234 562",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0701,
    geoLon: 22.2189,
    careLevel: 2,
  },
  {
    id: "s-063",
    firstName: "Jadwiga",
    lastName: "Krupa",
    dateOfBirth: new Date("1944-07-08"),
    gender: "K",
    address: "ul. Ogrodowa 6",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "563 234 563",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0656,
    geoLon: 22.2278,
    careLevel: 3,
  },
  {
    id: "s-064",
    firstName: "Marek",
    lastName: "Wierzbicki",
    dateOfBirth: new Date("1935-01-15"),
    gender: "M",
    address: "ul. Lwowska 17",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "564 234 564",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0689,
    geoLon: 22.2312,
    careLevel: 4,
  },
  {
    id: "s-065",
    firstName: "Danuta",
    lastName: "Olejnik",
    dateOfBirth: new Date("1947-09-22"),
    gender: "K",
    address: "ul. Parkowa 3",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "565 234 565",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0634,
    geoLon: 22.2156,
    careLevel: 5,
  },
  {
    id: "s-066",
    firstName: "Aleksander",
    lastName: "Palka",
    dateOfBirth: new Date("1931-04-07"),
    gender: "M",
    address: "ul. Polna 9",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "566 234 566",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0712,
    geoLon: 22.2245,
    careLevel: 6,
  },
  {
    id: "s-067",
    firstName: "Halina",
    lastName: "Zając",
    dateOfBirth: new Date("1940-11-30"),
    gender: "K",
    address: "ul. Słoneczna 14",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "567 234 567",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0667,
    geoLon: 22.2189,
    careLevel: 7,
  },
  {
    id: "s-068",
    firstName: "Kazimierz",
    lastName: "Wierzbicki",
    dateOfBirth: new Date("1943-06-14"),
    gender: "M",
    address: "ul. Kopernika 5",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "568 234 568",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0723,
    geoLon: 22.2267,
    careLevel: 4,
  },
  {
    id: "s-069",
    firstName: "Genowefa",
    lastName: "Piotrowska",
    dateOfBirth: new Date("1950-02-19"),
    gender: "K",
    address: "ul. Cicha 2",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "569 234 569",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0645,
    geoLon: 22.2134,
    careLevel: 3,
  },
  {
    id: "s-070",
    firstName: "Waldemar",
    lastName: "Kurek",
    dateOfBirth: new Date("1956-08-03"),
    gender: "M",
    address: "ul. Jasna 8",
    city: "Łańcut",
    postalCode: "37-100",
    phone: "570 234 570",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.07,
    geoLon: 22.23,
    careLevel: 2,
  },
  // ── Boguchwała ───────────────────────────────────────────────────────────
  {
    id: "s-071",
    firstName: "Teresa",
    lastName: "Bobek",
    dateOfBirth: new Date("1945-05-11"),
    gender: "K",
    address: "ul. Rynek 7",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "571 234 571",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9845,
    geoLon: 22.0789,
    careLevel: 3,
  },
  {
    id: "s-072",
    firstName: "Franciszek",
    lastName: "Polak",
    dateOfBirth: new Date("1937-12-02"),
    gender: "M",
    address: "ul. Kościelna 3",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "572 234 572",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 49.9867,
    geoLon: 22.0823,
    careLevel: 4,
  },
  {
    id: "s-073",
    firstName: "Wanda",
    lastName: "Chmura",
    dateOfBirth: new Date("1942-09-16"),
    gender: "K",
    address: "ul. Polna 11",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "573 234 573",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9823,
    geoLon: 22.0756,
    careLevel: 5,
  },
  {
    id: "s-074",
    firstName: "Leszek",
    lastName: "Janicki",
    dateOfBirth: new Date("1933-03-28"),
    gender: "M",
    address: "ul. Leśna 5",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "574 234 574",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 49.9889,
    geoLon: 22.0867,
    careLevel: 6,
  },
  {
    id: "s-075",
    firstName: "Elżbieta",
    lastName: "Slusarczyk",
    dateOfBirth: new Date("1949-07-07"),
    gender: "K",
    address: "ul. Ogrodowa 18",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "575 234 575",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 49.9801,
    geoLon: 22.0712,
    careLevel: 7,
  },
  {
    id: "s-076",
    firstName: "Bogdan",
    lastName: "Mazurek",
    dateOfBirth: new Date("1946-10-20"),
    gender: "M",
    address: "ul. Słoneczna 9",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "576 234 576",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9912,
    geoLon: 22.0845,
    careLevel: 2,
  },
  {
    id: "s-077",
    firstName: "Bronisława",
    lastName: "Wierzbicka",
    dateOfBirth: new Date("1939-01-15"),
    gender: "K",
    address: "ul. Kwiatowa 4",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "577 234 577",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9856,
    geoLon: 22.0734,
    careLevel: 4,
  },
  {
    id: "s-078",
    firstName: "Czesław",
    lastName: "Kot",
    dateOfBirth: new Date("1943-06-29"),
    gender: "M",
    address: "ul. Różana 6",
    city: "Boguchwała",
    postalCode: "36-040",
    phone: "578 234 578",
    identificationConfidence: "NEW_RECORD",
    geoLat: 49.9878,
    geoLon: 22.0901,
    careLevel: 5,
  },
  // ── Tyczyn ───────────────────────────────────────────────────────────────
  {
    id: "s-079",
    firstName: "Marianna",
    lastName: "Kędzior",
    dateOfBirth: new Date("1944-04-13"),
    gender: "K",
    address: "ul. Rynek 2",
    city: "Tyczyn",
    postalCode: "36-020",
    phone: "579 234 579",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9712,
    geoLon: 22.069,
    careLevel: 3,
  },
  {
    id: "s-080",
    firstName: "Piotr",
    lastName: "Jaworski",
    dateOfBirth: new Date("1936-08-24"),
    gender: "M",
    address: "ul. Kościuszki 7",
    city: "Tyczyn",
    postalCode: "36-020",
    phone: "580 234 580",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 49.9734,
    geoLon: 22.0723,
    careLevel: 4,
  },
  {
    id: "s-081",
    firstName: "Leokadia",
    lastName: "Gajda",
    dateOfBirth: new Date("1941-11-19"),
    gender: "K",
    address: "ul. Parkowa 4",
    city: "Tyczyn",
    postalCode: "36-020",
    phone: "581 234 581",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9689,
    geoLon: 22.0656,
    careLevel: 5,
  },
  {
    id: "s-082",
    firstName: "Mirosław",
    lastName: "Sroka",
    dateOfBirth: new Date("1938-02-06"),
    gender: "M",
    address: "ul. Lwowska 11",
    city: "Tyczyn",
    postalCode: "36-020",
    phone: "582 234 582",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 49.9756,
    geoLon: 22.0745,
    careLevel: 6,
  },
  {
    id: "s-083",
    firstName: "Józefa",
    lastName: "Paluch",
    dateOfBirth: new Date("1934-09-30"),
    gender: "K",
    address: "ul. Nowa 8",
    city: "Tyczyn",
    postalCode: "36-020",
    phone: "583 234 583",
    identificationConfidence: "NAME_DOB",
    geoLat: 49.9667,
    geoLon: 22.0712,
    careLevel: 7,
  },
  {
    id: "s-084",
    firstName: "Henryk",
    lastName: "Lisowski",
    dateOfBirth: new Date("1950-05-14"),
    gender: "M",
    address: "ul. Polna 3",
    city: "Tyczyn",
    postalCode: "36-020",
    phone: "584 234 584",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 49.9778,
    geoLon: 22.0678,
    careLevel: 2,
  },
  // ── Sokołów Małopolski ────────────────────────────────────────────────────
  {
    id: "s-085",
    firstName: "Anna",
    lastName: "Smolinska",
    dateOfBirth: new Date("1947-07-21"),
    gender: "K",
    address: "ul. Rynek 5",
    city: "Sokołów Małopolski",
    postalCode: "36-050",
    phone: "585 234 585",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1834,
    geoLon: 21.9723,
    careLevel: 3,
  },
  {
    id: "s-086",
    firstName: "Zygmunt",
    lastName: "Wroblewski",
    dateOfBirth: new Date("1935-10-03"),
    gender: "M",
    address: "ul. Kościelna 14",
    city: "Sokołów Małopolski",
    postalCode: "36-050",
    phone: "586 234 586",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.1856,
    geoLon: 21.9756,
    careLevel: 4,
  },
  {
    id: "s-087",
    firstName: "Stanisława",
    lastName: "Giemza",
    dateOfBirth: new Date("1943-03-15"),
    gender: "K",
    address: "ul. Ogrodowa 8",
    city: "Sokołów Małopolski",
    postalCode: "36-050",
    phone: "587 234 587",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.1812,
    geoLon: 21.9689,
    careLevel: 5,
  },
  {
    id: "s-088",
    firstName: "Marian",
    lastName: "Fryc",
    dateOfBirth: new Date("1939-12-28"),
    gender: "M",
    address: "ul. Leśna 3",
    city: "Sokołów Małopolski",
    postalCode: "36-050",
    phone: "588 234 588",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.1878,
    geoLon: 21.9801,
    careLevel: 6,
  },
  {
    id: "s-089",
    firstName: "Wiesława",
    lastName: "Ciolek",
    dateOfBirth: new Date("1945-06-09"),
    gender: "K",
    address: "ul. Polna 17",
    city: "Sokołów Małopolski",
    postalCode: "36-050",
    phone: "589 234 589",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.179,
    geoLon: 21.9667,
    careLevel: 1,
  },
  {
    id: "s-090",
    firstName: "Józef",
    lastName: "Pelczar",
    dateOfBirth: new Date("1932-09-22"),
    gender: "M",
    address: "ul. Kwiatowa 6",
    city: "Sokołów Małopolski",
    postalCode: "36-050",
    phone: "590 234 590",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.1901,
    geoLon: 21.9845,
    careLevel: 7,
  },
  // ── Rzeszów – dodatkowe centrum i osiedla ─────────────────────────────────
  {
    id: "s-091",
    firstName: "Krystyna",
    lastName: "Kalinowska",
    dateOfBirth: new Date("1953-02-10"),
    gender: "K",
    address: "ul. Handlowa 4",
    city: "Rzeszów",
    postalCode: "35-109",
    phone: "591 234 591",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.046,
    geoLon: 22.0145,
    careLevel: 2,
  },
  {
    id: "s-092",
    firstName: "Roman",
    lastName: "Jasinski",
    dateOfBirth: new Date("1942-07-16"),
    gender: "M",
    address: "ul. Przemyska 9",
    city: "Rzeszów",
    postalCode: "35-234",
    phone: "592 234 592",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0389,
    geoLon: 22.0189,
    careLevel: 4,
  },
  {
    id: "s-093",
    firstName: "Grażyna",
    lastName: "Majewska",
    dateOfBirth: new Date("1948-11-28"),
    gender: "K",
    address: "ul. Paderewskiego 6",
    city: "Rzeszów",
    postalCode: "35-005",
    phone: "593 234 593",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.043,
    geoLon: 22.0034,
    careLevel: 3,
  },
  {
    id: "s-094",
    firstName: "Eugeniusz",
    lastName: "Kasprzyk",
    dateOfBirth: new Date("1937-05-04"),
    gender: "M",
    address: "ul. Wysoka 12",
    city: "Rzeszów",
    postalCode: "35-113",
    phone: "594 234 594",
    identificationConfidence: "NEW_RECORD",
    geoLat: 50.0508,
    geoLon: 21.9956,
    careLevel: 5,
  },
  {
    id: "s-095",
    firstName: "Cecylia",
    lastName: "Drozdek",
    dateOfBirth: new Date("1944-08-18"),
    gender: "K",
    address: "ul. Okopowa 3",
    city: "Rzeszów",
    postalCode: "35-316",
    phone: "595 234 595",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0367,
    geoLon: 22.0112,
    careLevel: 6,
  },
  {
    id: "s-096",
    firstName: "Władysław",
    lastName: "Biały",
    dateOfBirth: new Date("1930-03-25"),
    gender: "M",
    address: "ul. Targowa 18",
    city: "Rzeszów",
    postalCode: "35-064",
    phone: "596 234 596",
    identificationConfidence: "NAME_DOB_EXTRA",
    geoLat: 50.0405,
    geoLon: 22.0167,
    careLevel: 7,
  },
  {
    id: "s-097",
    firstName: "Marianna",
    lastName: "Kolodziej",
    dateOfBirth: new Date("1956-10-07"),
    gender: "K",
    address: "ul. Szopena 21",
    city: "Rzeszów",
    postalCode: "35-055",
    phone: "597 234 597",
    identificationConfidence: "STAFF_CONFIRMED",
    geoLat: 50.0478,
    geoLon: 22.0089,
    careLevel: 3,
  },
  {
    id: "s-098",
    firstName: "Jerzy",
    lastName: "Dudek",
    dateOfBirth: new Date("1940-01-12"),
    gender: "M",
    address: "ul. Jagiellońska 5",
    city: "Rzeszów",
    postalCode: "35-025",
    phone: "598 234 598",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0421,
    geoLon: 21.9989,
    careLevel: 4,
  },
  {
    id: "s-099",
    firstName: "Irena",
    lastName: "Zawadzka",
    dateOfBirth: new Date("1946-04-29"),
    gender: "K",
    address: "ul. Batorego 8",
    city: "Rzeszów",
    postalCode: "35-005",
    phone: "599 234 599",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0356,
    geoLon: 22.0078,
    careLevel: 5,
  },
  {
    id: "s-100",
    firstName: "Andrzej",
    lastName: "Lukasik",
    dateOfBirth: new Date("1939-09-11"),
    gender: "M",
    address: "ul. Królewska 14",
    city: "Rzeszów",
    postalCode: "35-006",
    phone: "600 234 600",
    identificationConfidence: "NAME_DOB",
    geoLat: 50.0498,
    geoLon: 22.0201,
    careLevel: 6,
  },
];

// ─── Providers data (25 providers in Rzeszów area) ────────────────────────────
interface ProviderData {
  id: string;
  name: string;
  type: string;
  city: string;
  address: string;
  phone: string;
  coverageType: "ADDRESS_ONLY" | "RADIUS" | "CITY_LIST";
  coverageRadius?: number;
  coverageCities?: string[];
  status: "ACTIVE" | "PENDING" | "SUSPENDED";
  capacity: number;
  geoLat: number;
  geoLon: number;
  services: Array<{
    serviceCode: string;
    priceMin: number;
    priceMax: number;
    priceUnit: string;
  }>;
}

const PROVIDERS: ProviderData[] = [
  {
    id: "provider-1",
    name: "CUS Rzeszów – Centrum Usług Środowiskowych",
    type: "Centrum Usług Środowiskowych",
    city: "Rzeszów",
    address: "ul. Kopernika 16",
    phone: "17 875 45 00",
    coverageType: "CITY_LIST",
    coverageCities: ["Rzeszów", "Głogów Małopolski", "Boguchwała"],
    status: "ACTIVE",
    capacity: 80,
    geoLat: 50.0412,
    geoLon: 22.0001,
    services: [
      {
        serviceCode: "Opieka dzienna",
        priceMin: 800,
        priceMax: 1200,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Usługi opiekuńcze w domu",
        priceMin: 25,
        priceMax: 40,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Aktywizacja i integracja",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-2",
    name: 'Dom Seniora "Złota Jesień" Rzeszów',
    type: "Prywatny dom seniora",
    city: "Rzeszów",
    address: "ul. Dąbrowskiego 34",
    phone: "17 875 45 01",
    coverageType: "ADDRESS_ONLY",
    status: "ACTIVE",
    capacity: 36,
    geoLat: 50.0445,
    geoLon: 22.0156,
    services: [
      {
        serviceCode: "Całodobowa opieka",
        priceMin: 3500,
        priceMax: 5500,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Pielęgniarstwo",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Rehabilitacja",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Wyżywienie (3 posiłki)",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-3",
    name: 'Opieka Domowa "Pro Familia" Rzeszów',
    type: "Firma opieki domowej",
    city: "Rzeszów",
    address: "ul. Lwowska 18",
    phone: "17 875 45 02",
    coverageType: "RADIUS",
    coverageRadius: 25,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0367,
    geoLon: 21.9923,
    services: [
      {
        serviceCode: "Usługi opiekuńcze w domu",
        priceMin: 22,
        priceMax: 35,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Pomoc w codziennych czynnościach",
        priceMin: 22,
        priceMax: 35,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Towarzyszenie",
        priceMin: 18,
        priceMax: 28,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-4",
    name: "Wolontariat Parafialny CARITAS Rzeszów",
    type: "Wolontariat / NGO",
    city: "Rzeszów",
    address: "ul. Fary 1",
    phone: "17 875 45 03",
    coverageType: "CITY_LIST",
    coverageCities: ["Rzeszów", "Boguchwała", "Tyczyn"],
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0631,
    geoLon: 21.9956,
    services: [
      {
        serviceCode: "Pomoc wolontariacka",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Dowóz posiłków",
        priceMin: 0,
        priceMax: 5,
        priceUnit: "dzien",
      },
      {
        serviceCode: "Towarzyszenie",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-5",
    name: "SafeAge Teleopieka",
    type: "Teleopieka / monitoring",
    city: "Rzeszów",
    address: "ul. Hetmańska 120",
    phone: "17 875 45 04",
    coverageType: "RADIUS",
    coverageRadius: 60,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.049,
    geoLon: 22.0112,
    services: [
      {
        serviceCode: "Monitoring 24h",
        priceMin: 80,
        priceMax: 150,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Opaska życia SOS",
        priceMin: 60,
        priceMax: 100,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Teleporady medyczne",
        priceMin: 40,
        priceMax: 80,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-6",
    name: 'Dom Pomocy Społecznej "Zamek" Rzeszów',
    type: "Dom Pomocy Społecznej",
    city: "Rzeszów",
    address: "ul. Zamkowa 7",
    phone: "17 862 11 00",
    coverageType: "ADDRESS_ONLY",
    status: "ACTIVE",
    capacity: 120,
    geoLat: 50.0423,
    geoLon: 22.0089,
    services: [
      {
        serviceCode: "Całodobowa opieka",
        priceMin: 3200,
        priceMax: 4800,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Opieka specjalistyczna",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Pielęgniarstwo",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Terapia zajęciowa",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-7",
    name: "Centrum Aktywizacji Seniora Rzeszów",
    type: "Centrum aktywizacji seniora",
    city: "Rzeszów",
    address: "ul. Słowackiego 24",
    phone: "17 854 22 11",
    coverageType: "CITY_LIST",
    coverageCities: ["Rzeszów"],
    status: "ACTIVE",
    capacity: 60,
    geoLat: 50.0445,
    geoLon: 22.0034,
    services: [
      {
        serviceCode: "Zajęcia aktywizujące",
        priceMin: 50,
        priceMax: 150,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Rehabilitacja",
        priceMin: 60,
        priceMax: 120,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Opieka dzienna",
        priceMin: 400,
        priceMax: 800,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Dożywianie",
        priceMin: 200,
        priceMax: 400,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-8",
    name: 'Fundacja "Srebrny Wiek" Rzeszów',
    type: "Fundacja / NGO",
    city: "Rzeszów",
    address: "ul. 3 Maja 15",
    phone: "17 844 33 22",
    coverageType: "RADIUS",
    coverageRadius: 40,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0401,
    geoLon: 22.0056,
    services: [
      {
        serviceCode: "Asystent osoby starszej",
        priceMin: 0,
        priceMax: 20,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Grupy wsparcia",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Pomoc prawna i socjalna",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-9",
    name: 'NZOZ Hospicjum "Nadziei" Rzeszów',
    type: "Hospicjum domowe",
    city: "Rzeszów",
    address: "ul. Szopena 51",
    phone: "17 832 44 55",
    coverageType: "RADIUS",
    coverageRadius: 30,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0478,
    geoLon: 22.0023,
    services: [
      {
        serviceCode: "Opieka paliatywna",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Pielęgniarstwo specjalistyczne",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Wsparcie psychologiczne",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-10",
    name: "Reha-Med Centrum Rehabilitacji",
    type: "Centrum rehabilitacji",
    city: "Rzeszów",
    address: "ul. Rejtana 8",
    phone: "17 852 66 77",
    coverageType: "ADDRESS_ONLY",
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0389,
    geoLon: 22.0167,
    services: [
      {
        serviceCode: "Fizjoterapia",
        priceMin: 80,
        priceMax: 150,
        priceUnit: "wizyta",
      },
      {
        serviceCode: "Rehabilitacja ruchowa",
        priceMin: 80,
        priceMax: 150,
        priceUnit: "wizyta",
      },
      {
        serviceCode: "Masaż leczniczy",
        priceMin: 60,
        priceMax: 100,
        priceUnit: "wizyta",
      },
    ],
  },
  {
    id: "provider-11",
    name: 'Klub Seniora "Tęcza" – os. Nowe Miasto',
    type: "Klub seniora",
    city: "Rzeszów",
    address: "ul. Hetmańska 66",
    phone: "17 866 11 44",
    coverageType: "CITY_LIST",
    coverageCities: ["Rzeszów"],
    status: "ACTIVE",
    capacity: 40,
    geoLat: 50.0534,
    geoLon: 22.0045,
    services: [
      {
        serviceCode: "Zajęcia kulturalne",
        priceMin: 30,
        priceMax: 60,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Gimnastyka seniorek",
        priceMin: 30,
        priceMax: 60,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Dożywianie",
        priceMin: 150,
        priceMax: 250,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-12",
    name: 'Opieka Domowa "Troskliwa Dłoń"',
    type: "Firma opieki domowej",
    city: "Rzeszów",
    address: "ul. Krakowska 91",
    phone: "17 877 22 33",
    coverageType: "RADIUS",
    coverageRadius: 20,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0356,
    geoLon: 21.9945,
    services: [
      {
        serviceCode: "Usługi opiekuńcze w domu",
        priceMin: 20,
        priceMax: 32,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Opieka nocna",
        priceMin: 120,
        priceMax: 200,
        priceUnit: "noc",
      },
      {
        serviceCode: "Pomoc w leczeniu i rehabilitacji",
        priceMin: 25,
        priceMax: 40,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-13",
    name: 'Transport Medyczny "MediTrans" Rzeszów',
    type: "Transport medyczny",
    city: "Rzeszów",
    address: "ul. Podkarpacka 15",
    phone: "17 899 00 11",
    coverageType: "RADIUS",
    coverageRadius: 50,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0512,
    geoLon: 22.0078,
    services: [
      {
        serviceCode: "Transport na rehabilitację",
        priceMin: 20,
        priceMax: 60,
        priceUnit: "przejazd",
      },
      {
        serviceCode: "Transport do lekarza",
        priceMin: 20,
        priceMax: 60,
        priceUnit: "przejazd",
      },
      {
        serviceCode: "Transport sanitarny",
        priceMin: 80,
        priceMax: 200,
        priceUnit: "przejazd",
      },
    ],
  },
  {
    id: "provider-14",
    name: "PCK – Wolontariat Rzeszów",
    type: "Wolontariat / NGO",
    city: "Rzeszów",
    address: "ul. Baldachówka 5",
    phone: "17 853 08 75",
    coverageType: "CITY_LIST",
    coverageCities: ["Rzeszów", "Głogów Małopolski", "Łańcut"],
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0422,
    geoLon: 22.0112,
    services: [
      {
        serviceCode: "Pomoc wolontariacka",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Dożywianie – obiady",
        priceMin: 0,
        priceMax: 3,
        priceUnit: "dzien",
      },
      {
        serviceCode: "Paczki żywnościowe",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-15",
    name: 'Dom Seniora "Podkarpacie" Rzeszów',
    type: "Prywatny dom seniora",
    city: "Rzeszów",
    address: "ul. Przybyszówka 32",
    phone: "17 871 55 66",
    coverageType: "ADDRESS_ONLY",
    status: "ACTIVE",
    capacity: 48,
    geoLat: 50.0578,
    geoLon: 21.9767,
    services: [
      {
        serviceCode: "Całodobowa opieka",
        priceMin: 3800,
        priceMax: 5800,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Pielęgniarstwo",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Rehabilitacja",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-16",
    name: "CUS Głogów Małopolski",
    type: "Centrum Usług Środowiskowych",
    city: "Głogów Małopolski",
    address: "ul. Rynek 20",
    phone: "17 851 40 00",
    coverageType: "CITY_LIST",
    coverageCities: ["Głogów Małopolski", "Rzeszów"],
    status: "ACTIVE",
    capacity: 50,
    geoLat: 50.1634,
    geoLon: 22.0201,
    services: [
      {
        serviceCode: "Opieka dzienna",
        priceMin: 600,
        priceMax: 1000,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Usługi opiekuńcze w domu",
        priceMin: 20,
        priceMax: 35,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Aktywizacja i integracja",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-17",
    name: 'Stowarzyszenie "Aktywni Seniorzy" Łańcut',
    type: "Fundacja / NGO",
    city: "Łańcut",
    address: "ul. Zamkowa 3",
    phone: "17 225 56 78",
    coverageType: "CITY_LIST",
    coverageCities: ["Łańcut", "Rzeszów"],
    status: "ACTIVE",
    capacity: 30,
    geoLat: 50.0689,
    geoLon: 22.2189,
    services: [
      {
        serviceCode: "Zajęcia aktywizujące",
        priceMin: 40,
        priceMax: 100,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Wolontariat sąsiedzki",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Wsparcie psychologiczne",
        priceMin: 50,
        priceMax: 100,
        priceUnit: "wizyta",
      },
    ],
  },
  {
    id: "provider-18",
    name: 'Dom Seniora "Zamkowy" Łańcut',
    type: "Prywatny dom seniora",
    city: "Łańcut",
    address: "ul. Kościuszki 18",
    phone: "17 225 67 89",
    coverageType: "ADDRESS_ONLY",
    status: "ACTIVE",
    capacity: 28,
    geoLat: 50.0712,
    geoLon: 22.2278,
    services: [
      {
        serviceCode: "Całodobowa opieka",
        priceMin: 3600,
        priceMax: 5200,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Rehabilitacja",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Pielęgniarstwo",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-19",
    name: "DPS Boguchwała",
    type: "Dom Pomocy Społecznej",
    city: "Boguchwała",
    address: "ul. Suszyckich 1",
    phone: "17 875 01 00",
    coverageType: "ADDRESS_ONLY",
    status: "ACTIVE",
    capacity: 80,
    geoLat: 49.9878,
    geoLon: 22.0856,
    services: [
      {
        serviceCode: "Całodobowa opieka",
        priceMin: 3000,
        priceMax: 4500,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Opieka specjalistyczna",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Terapia zajęciowa",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-20",
    name: "CUS Boguchwała",
    type: "Centrum Usług Środowiskowych",
    city: "Boguchwała",
    address: "ul. Rynek 4",
    phone: "17 875 02 00",
    coverageType: "CITY_LIST",
    coverageCities: ["Boguchwała", "Tyczyn", "Rzeszów"],
    status: "ACTIVE",
    capacity: 40,
    geoLat: 49.9845,
    geoLon: 22.0767,
    services: [
      {
        serviceCode: "Usługi opiekuńcze w domu",
        priceMin: 20,
        priceMax: 35,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Aktywizacja i integracja",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Dowóz posiłków",
        priceMin: 5,
        priceMax: 10,
        priceUnit: "dzien",
      },
    ],
  },
  {
    id: "provider-21",
    name: "NZOZ Centrum Zdrowia Seniora Tyczyn",
    type: "NZOZ / Przychodnia",
    city: "Tyczyn",
    address: "ul. Rynek 12",
    phone: "17 221 12 34",
    coverageType: "CITY_LIST",
    coverageCities: ["Tyczyn", "Boguchwała", "Rzeszów"],
    status: "ACTIVE",
    capacity: 0,
    geoLat: 49.9734,
    geoLon: 22.0712,
    services: [
      {
        serviceCode: "Porady geriatryczne",
        priceMin: 80,
        priceMax: 150,
        priceUnit: "wizyta",
      },
      {
        serviceCode: "Pielęgniarstwo środowiskowe",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "wizyta",
      },
      {
        serviceCode: "Fizjoterapia",
        priceMin: 70,
        priceMax: 120,
        priceUnit: "wizyta",
      },
    ],
  },
  {
    id: "provider-22",
    name: 'Fundacja "Pomocna Dłoń" Sokołów Małopolski',
    type: "Fundacja / NGO",
    city: "Sokołów Małopolski",
    address: "ul. Rynek 8",
    phone: "17 582 12 00",
    coverageType: "CITY_LIST",
    coverageCities: ["Sokołów Małopolski", "Rzeszów"],
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.1856,
    geoLon: 21.9745,
    services: [
      {
        serviceCode: "Pomoc wolontariacka",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Asystent osoby starszej",
        priceMin: 0,
        priceMax: 15,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-23",
    name: 'Opieka Domowa "Senior Plus" Głogów Małopolski',
    type: "Firma opieki domowej",
    city: "Głogów Małopolski",
    address: "ul. Leśna 9",
    phone: "17 851 88 99",
    coverageType: "RADIUS",
    coverageRadius: 20,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.1601,
    geoLon: 22.0289,
    services: [
      {
        serviceCode: "Usługi opiekuńcze w domu",
        priceMin: 22,
        priceMax: 36,
        priceUnit: "godzina",
      },
      {
        serviceCode: "Pomoc w codziennych czynnościach",
        priceMin: 22,
        priceMax: 36,
        priceUnit: "godzina",
      },
    ],
  },
  {
    id: "provider-24",
    name: "CareConnect Teleopieka – Podkarpacie",
    type: "Teleopieka / monitoring",
    city: "Rzeszów",
    address: "ul. Paderewskiego 22",
    phone: "17 890 11 22",
    coverageType: "RADIUS",
    coverageRadius: 80,
    status: "ACTIVE",
    capacity: 0,
    geoLat: 50.0432,
    geoLon: 22.0012,
    services: [
      {
        serviceCode: "Monitoring 24h",
        priceMin: 70,
        priceMax: 130,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Opaska życia SOS",
        priceMin: 50,
        priceMax: 90,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Teleporady medyczne",
        priceMin: 30,
        priceMax: 60,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Kontrola przyjmowania leków",
        priceMin: 40,
        priceMax: 80,
        priceUnit: "miesiac",
      },
    ],
  },
  {
    id: "provider-25",
    name: 'Klub Seniora "Jutrzenka" os. Pobitno',
    type: "Klub seniora",
    city: "Rzeszów",
    address: "ul. Pobitno 44",
    phone: "17 856 77 88",
    coverageType: "CITY_LIST",
    coverageCities: ["Rzeszów"],
    status: "ACTIVE",
    capacity: 35,
    geoLat: 50.0501,
    geoLon: 22.0189,
    services: [
      {
        serviceCode: "Zajęcia kulturalne",
        priceMin: 30,
        priceMax: 60,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Gimnastyka seniorek",
        priceMin: 30,
        priceMax: 60,
        priceUnit: "miesiac",
      },
      {
        serviceCode: "Grupy wsparcia",
        priceMin: 0,
        priceMax: 0,
        priceUnit: "miesiac",
      },
    ],
  },
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Seeding database...");

  // Organization
  const org = await prisma.organization.upsert({
    where: { slug: "solaris" },
    update: {},
    create: {
      name: "Gmina Rzeszów",
      slug: "solaris",
      address: "Rynek 1",
      city: "Rzeszów",
      logoText: "GR",
    },
  });
  console.log("Organization:", org.name);

  // Admin user
  const hashedPassword = await bcrypt.hash("Admin123!", 12);
  const admin = await prisma.user.upsert({
    where: { email: "admin@example.com" },
    update: {},
    create: {
      organizationId: org.id,
      email: "admin@example.com",
      name: "Administrator Systemowy",
      password: hashedPassword,
      role: "ADMIN",
      status: "ACTIVE",
    },
  });
  console.log("Admin:", admin.email);

  // Survey template K1-K4
  const template = await prisma.surveyTemplate.upsert({
    where: { id: "template-k1k4-default" },
    update: {},
    create: {
      id: "template-k1k4-default",
      organizationId: org.id,
      name: "Kwestionariusz K1-K4",
      description:
        "Standardowy kwestionariusz oceny potrzeb opiekunczych seniorow",
      version: 1,
      status: "PUBLISHED",
      isDefault: true,
      publishedAt: new Date(),
    },
  });
  console.log("Template:", template.name);

  const sections = [
    {
      id: "section-k1",
      code: "K1",
      title: "Sytuacja zyciowa i wsparcie",
      order: 1,
      maxScore: 24,
      questions: [
        {
          code: "k1_1",
          text: "Sposob zamieszkania",
          order: 1,
          options: [
            { value: 0, label: "Sam/a - nikt nie odwiedza regularnie" },
            { value: 1, label: "Sam/a - ktos odwiedza okazjonalnie" },
            { value: 2, label: "Z osoba majaca ograniczone mozliwosci pomocy" },
            {
              value: 3,
              label: "Z osobami zdolnymi do regularnej codziennej pomocy",
            },
          ],
        },
        {
          code: "k1_2",
          text: "Realna dostepnosc pomocy w ciagu doby",
          order: 2,
          options: [
            { value: 0, label: "Brak osoby mogacej pomagac codziennie" },
            { value: 1, label: "Pomoc krocej niz 1 godz. dziennie" },
            { value: 2, label: "Pomoc 1-4 godziny dziennie" },
            {
              value: 3,
              label: "Pomoc ponad 4 godz. lub latwa do zorganizowania",
            },
          ],
        },
        {
          code: "k1_3",
          text: "Sprawnosc i obciazenie glownego opiekuna",
          order: 3,
          options: [
            {
              value: 0,
              label: "Brak opiekuna lub opiekun chory / mocno przeciazony",
            },
            {
              value: 1,
              label:
                "Opiekun z istotnymi ograniczeniami lub silnie przeciazony",
            },
            {
              value: 2,
              label: "Opiekun w umiarkowanym stanie, czasem przeciazony",
            },
            { value: 3, label: "Opiekun sprawny, dysponuje czasem i zdrowiem" },
          ],
        },
        {
          code: "k1_4",
          text: "Dostepnosc rodziny spoza wspolnego domu",
          order: 4,
          options: [
            { value: 0, label: "Rodzina dalej niz 60 min lub brak rodziny" },
            { value: 1, label: "Rodzina 30-60 min, przyjezdza sporadycznie" },
            {
              value: 2,
              label: "Rodzina do 30 min - wsparcie kilka razy w tygodniu",
            },
            {
              value: 3,
              label: "Rodzina bardzo blisko - dostepna w razie potrzeby",
            },
          ],
        },
        {
          code: "k1_5",
          text: "Wsparcie ssiedzkie i lokalne",
          order: 5,
          options: [
            { value: 0, label: "Brak realnego wsparcia" },
            { value: 1, label: "Sporadyczna pomoc od sasiadow lub instytucji" },
            {
              value: 2,
              label: "Staly kontakt z sasiadami lub okazjonalne uslugi",
            },
            {
              value: 3,
              label: "Dobrze dzialajaca siec (sasiedzi, OPS, wolontariusze)",
            },
          ],
        },
        {
          code: "k1_6",
          text: "Bariery architektoniczne przy wyjsciu z domu",
          order: 6,
          options: [
            { value: 0, label: "Powazne bariery (3. pietro bez windy)" },
            { value: 1, label: "Znaczne bariery (1 pietro bez windy)" },
            { value: 2, label: "Niewielkie bariery (pojedyncze stopnie)" },
            { value: 3, label: "Brak barier (winda / parter, porece)" },
          ],
        },
        {
          code: "k1_7",
          text: "Dostep do uslug (lekarz, apteka, sklep)",
          order: 7,
          options: [
            { value: 0, label: "Wylacznie transportem zorganizowanym" },
            { value: 1, label: "Dlugi marsz lub dwa srodki transportu" },
            { value: 2, label: "Krotki spacer lub jeden srodek transportu" },
            { value: 3, label: "Bardzo blisko lub z dowozem do domu" },
          ],
        },
        {
          code: "k1_8",
          text: "Mozliwosci finansowe - oplacenie opieki",
          order: 8,
          options: [
            { value: 0, label: "Brak realnych mozliwosci" },
            { value: 1, label: "Bardzo ograniczone" },
            { value: 2, label: "Mozliwosc sfinansowania czesci uslug" },
            { value: 3, label: "Dobra mozliwosc finansowania" },
          ],
        },
      ],
    },
    {
      id: "section-k2a",
      code: "K2A",
      title: "Samodzielnosc ADL",
      order: 2,
      maxScore: 30,
      questions: [
        {
          code: "k2_1",
          text: "Samodzielne jedzenie i picie",
          order: 1,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_2",
          text: "Wstawanie z lozka / siadanie na krzesle",
          order: 2,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_3",
          text: "Chodzenie po mieszkaniu",
          order: 3,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_4",
          text: "Wchodzenie i schodzenie po schodach",
          order: 4,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_5",
          text: "Korzystanie z toalety (przejscie, siadanie, higiena)",
          order: 5,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_6",
          text: "Kontrola oddawania moczu",
          order: 6,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_7",
          text: "Kontrola oddawania stolca",
          order: 7,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_8",
          text: "Ubieranie i rozbieranie sie",
          order: 8,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_9",
          text: "Kapiel i mycie calego ciala",
          order: 9,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
        {
          code: "k2_10",
          text: "Codzienna higiena osobista (twarz, zeby, czesanie)",
          order: 10,
          options: [
            { value: 0, label: "Wymaga pelnej opieki" },
            { value: 1, label: "Przy duzej pomocy" },
            { value: 2, label: "Przy niewielkiej pomocy / nadzorze" },
            { value: 3, label: "Samodzielnie" },
          ],
        },
      ],
    },
    {
      id: "section-k2bc",
      code: "K2BC",
      title: "Orientacja, pamiec i komunikacja",
      order: 3,
      maxScore: 21,
      questions: [
        {
          code: "k2_11",
          text: "Orientacja w miejscu",
          order: 1,
          options: [
            { value: 0, label: "Gubi sie w domu, zupelnie nie wie gdzie jest" },
            { value: 1, label: "Czesto sie myli, wymaga prowadzenia" },
            { value: 2, label: "Czasem sie myli, generalnie wie gdzie jest" },
            { value: 3, label: "W pelni zorientowany/a" },
          ],
        },
        {
          code: "k2_12",
          text: "Orientacja w czasie (dzien tygodnia, pora dnia)",
          order: 2,
          options: [
            { value: 0, label: "Nie orientuje sie, myli dzien z noca" },
            { value: 1, label: "Czesto myli dni i pory dnia" },
            {
              value: 2,
              label: "Czasem sie myli, po przypomnieniu orientuje sie",
            },
            { value: 3, label: "Orientuje sie prawidlowo" },
          ],
        },
        {
          code: "k2_13",
          text: "Rozpoznawanie bliskich i opiekunow",
          order: 3,
          options: [
            { value: 0, label: "Czesto nie rozpoznaje, myli osoby" },
            { value: 1, label: "Zdarza sie mylenie, potrzebuje podpowiedzi" },
            { value: 2, label: "Zwykle rozpoznaje, pojedyncze pomylki" },
            { value: 3, label: "Bez problemu rozpoznaje bliskich" },
          ],
        },
        {
          code: "k2_14",
          text: "Pamiec krotkotrwala (informacje z ostatnich godzin)",
          order: 4,
          options: [
            { value: 0, label: "Nie pamięta, wymaga stalego nadzoru" },
            {
              value: 1,
              label: "Duze trudnosci, czesto zapomina podstawowe rzeczy",
            },
            {
              value: 2,
              label: "Umiarkowane problemy, czesto potrzebuje przypomnienia",
            },
            { value: 3, label: "Pamiec prawidlowa lub niewielkie zapominanie" },
          ],
        },
        {
          code: "k2_15",
          text: "Komunikowanie potrzeb",
          order: 5,
          options: [
            { value: 0, label: "Brak mozliwosci komunikacji" },
            { value: 1, label: "Utrudniona, wymaga stalej interpretacji" },
            {
              value: 2,
              label: "Komunikuje sie z trudnosciami, ale skutecznie",
            },
            { value: 3, label: "Komunikuje sie jasno i samodzielnie" },
          ],
        },
        {
          code: "k2_16",
          text: "Sluch (z aparatem jesli uzywa)",
          order: 6,
          options: [
            { value: 0, label: "Powazne problemy, nie slyszy rozmowy" },
            {
              value: 1,
              label: "Znaczne trudnosci, czesto prosi o powtorzenie",
            },
            { value: 2, label: "Niewielkie trudnosci" },
            { value: 3, label: "Wystarczajacy do codziennego funkcjonowania" },
          ],
        },
        {
          code: "k2_17",
          text: "Wzrok (z okularami jesli uzywa)",
          order: 7,
          options: [
            { value: 0, label: "Powazne problemy ograniczajace czynnosci" },
            { value: 1, label: "Znaczne trudnosci" },
            { value: 2, label: "Niewielkie trudnosci" },
            { value: 3, label: "Wystarczajacy do codziennego funkcjonowania" },
          ],
        },
      ],
    },
    {
      id: "section-k3",
      code: "K3",
      title: "Funkcjonowanie poza domem",
      order: 4,
      maxScore: 30,
      questions: [
        {
          code: "k3_1",
          text: "Wychodzenie z domu (drzwi, schody, dojscie)",
          order: 1,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_2",
          text: "Dojscie do sklepu lub punktu uslugowego",
          order: 2,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_3",
          text: "Samodzielne zakupy (wybor, platnosc)",
          order: 3,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_4",
          text: "Korzystanie z transportu (autobus, taksowka)",
          order: 4,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_5",
          text: "Poruszanie sie po znajomej okolicy",
          order: 5,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_6",
          text: "Zalatwanie spraw urzedowych i bankowych",
          order: 6,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_7",
          text: "Utrzymywanie kontaktow spolecznych",
          order: 7,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_8",
          text: "Aktywnosci poza domem (spacery, rehabilitacja)",
          order: 8,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_9",
          text: "Korzystanie z telefonu i komunikatorow",
          order: 9,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
        {
          code: "k3_10",
          text: "Radzenie sobie w naglych sytuacjach poza domem",
          order: 10,
          options: [
            { value: 0, label: "Nie wykonuje / nie wychodzi wcale" },
            {
              value: 1,
              label: "Wylacznie z bezposrednia pomoca towarzyszacej osoby",
            },
            {
              value: 2,
              label: "Z czesciowa pomoca (ktos organizuje, przypomina)",
            },
            { value: 3, label: "Samodzielnie bez pomocy" },
          ],
        },
      ],
    },
    {
      id: "section-k4",
      code: "K4",
      title: "Bezpieczenstwo i dostosowanie domu",
      order: 5,
      maxScore: 30,
      questions: [
        {
          code: "k4_1",
          text: "Podlogi i sliskosc (dywany, kable, progi)",
          order: 1,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_2",
          text: "Szerokosc przejsc i ustawienie mebli",
          order: 2,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_3",
          text: "Oswietlenie nocne (korytarz, lazienka, sypialnia)",
          order: 3,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_4",
          text: "Lazienka - prysznic/wanna, uchwyty, maty",
          order: 4,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_5",
          text: "Toaleta - wysokosc, uchwyty, dostep",
          order: 5,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_6",
          text: "Lozko - wysokosc i dostep",
          order: 6,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_7",
          text: "Kuchnia - rozmieszczenie rzeczy",
          order: 7,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_8",
          text: "Schody - porece, oswietlenie",
          order: 8,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_9",
          text: "Czujniki dymu, czadu lub gazu",
          order: 9,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
        {
          code: "k4_10",
          text: "System wzywania pomocy (guzik, telefon pod reka)",
          order: 10,
          options: [
            { value: 0, label: "Brak dostosowania / bardzo niebezpieczne" },
            { value: 1, label: "Istotne braki, wysokie ryzyko wypadku" },
            { value: 2, label: "Czesciowe dostosowanie, umiarkowane ryzyko" },
            { value: 3, label: "Dobrze dostosowane, niskie ryzyko" },
          ],
        },
      ],
    },
  ];

  for (const sectionData of sections) {
    const { questions, ...sectionFields } = sectionData;
    const section = await prisma.templateSection.upsert({
      where: { id: sectionFields.id },
      update: {},
      create: { ...sectionFields, templateId: template.id },
    });
    for (const q of questions) {
      await prisma.templateQuestion.upsert({
        where: { id: `${sectionFields.id}-${q.code}` },
        update: {},
        create: {
          id: `${sectionFields.id}-${q.code}`,
          sectionId: section.id,
          code: q.code,
          text: q.text,
          order: q.order,
          isRequired: true,
          options: q.options,
        },
      });
    }
  }
  console.log("Template sections and questions: OK");

  // ── Seniors (100) ──────────────────────────────────────────────────────────
  for (const s of SENIORS) {
    await prisma.senior.upsert({
      where: { id: s.id },
      update: { geoLat: s.geoLat, geoLon: s.geoLon, city: s.city },
      create: {
        id: s.id,
        organizationId: org.id,
        firstName: s.firstName,
        lastName: s.lastName,
        dateOfBirth: s.dateOfBirth,
        gender: s.gender,
        address: s.address,
        city: s.city,
        postalCode: s.postalCode,
        phone: s.phone,
        identificationConfidence: s.identificationConfidence,
        geoLat: s.geoLat,
        geoLon: s.geoLon,
      },
    });
  }
  console.log(`Seniors upserted: ${SENIORS.length}`);

  // ── Providers (25) ─────────────────────────────────────────────────────────
  for (const p of PROVIDERS) {
    await prisma.provider.upsert({
      where: { id: p.id },
      update: {
        geoLat: p.geoLat,
        geoLon: p.geoLon,
        city: p.city,
        name: p.name,
        status: p.status,
      },
      create: {
        id: p.id,
        organizationId: org.id,
        name: p.name,
        type: p.type,
        city: p.city,
        address: p.address,
        phone: p.phone,
        coverageType: p.coverageType,
        coverageRadius: p.coverageRadius ?? null,
        coverageCities: p.coverageCities ?? Prisma.JsonNull,
        status: p.status,
        capacity: p.capacity,
        geoLat: p.geoLat,
        geoLon: p.geoLon,
      },
    });
    // Upsert services
    for (const svc of p.services) {
      await prisma.providerService.upsert({
        where: {
          providerId_serviceCode: {
            providerId: p.id,
            serviceCode: svc.serviceCode,
          },
        },
        update: {},
        create: {
          providerId: p.id,
          serviceCode: svc.serviceCode,
          priceMin: svc.priceMin,
          priceMax: svc.priceMax,
          priceUnit: svc.priceUnit,
        },
      });
    }
  }
  console.log(`Providers upserted: ${PROVIDERS.length}`);

  // ── Provider availability (today) ─────────────────────────────────────────
  const today = new Date().toISOString().split("T")[0];
  const availData = [
    { id: "provider-1", status: "AVAILABLE" as const, freePlaces: 12 },
    { id: "provider-2", status: "LIMITED" as const, freePlaces: 3 },
    { id: "provider-3", status: "AVAILABLE" as const, freePlaces: 0 },
    { id: "provider-6", status: "LIMITED" as const, freePlaces: 5 },
    { id: "provider-7", status: "AVAILABLE" as const, freePlaces: 15 },
    { id: "provider-16", status: "AVAILABLE" as const, freePlaces: 8 },
    { id: "provider-19", status: "FULL" as const, freePlaces: 0 },
  ];
  for (const a of availData) {
    await prisma.providerAvailability.upsert({
      where: { providerId_date: { providerId: a.id, date: today } },
      update: {},
      create: {
        providerId: a.id,
        date: today,
        status: a.status,
        freePlaces: a.freePlaces,
      },
    });
  }

  // ── Surveys (100 – one per senior) ─────────────────────────────────────────
  // Spread survey dates over the last 12 months
  let surveysCreated = 0;
  let alertsCreated = 0;

  for (let i = 0; i < SENIORS.length; i++) {
    const senior = SENIORS[i];
    const level = senior.careLevel;
    const scores = SCORE_PROFILES[level];

    // Vary dates: distribute across last 12 months
    const daysAgo = Math.floor((i / SENIORS.length) * 365);
    const surveyDate = new Date();
    surveyDate.setDate(surveyDate.getDate() - daysAgo);

    const surveyId = `survey-${senior.id}`;

    await prisma.survey.upsert({
      where: { id: surveyId },
      update: {},
      create: {
        id: surveyId,
        organizationId: org.id,
        templateId: template.id,
        seniorId: senior.id,
        filledById: admin.id,
        status: "COMPLETED",
        careLevel: level,
        k1Score: scores.k1,
        k2Score: scores.k2,
        k3Score: scores.k3,
        k4Score: scores.k4,
        completedAt: surveyDate,
        createdAt: surveyDate,
      },
    });
    surveysCreated++;

    // Create alert for high care levels (5, 6, 7)
    if (level >= 5) {
      const alertId = `alert-${senior.id}`;
      await prisma.alert.upsert({
        where: { id: alertId },
        update: {},
        create: {
          id: alertId,
          organizationId: org.id,
          surveyId: surveyId,
          careLevel: level,
          status: level === 7 ? "OPEN" : level === 6 ? "OPEN" : "IN_PROGRESS",
          createdAt: surveyDate,
        },
      });
      alertsCreated++;
    }
  }

  console.log(`Surveys created: ${surveysCreated}`);
  console.log(`Alerts created: ${alertsCreated}`);

  // ── Fix existing surveys for first 3 seniors (convert raw scores → %) ──────
  // The main loop stored raw SCORE_PROFILES values; these 3 need percentage values
  // so the trend chart displays correctly.
  const firstThreeFixes = [
    // s-001 Janina Kowalska — current = best state (level 1)
    {
      id: "survey-s-001",
      k1Score: 88,
      k2Score: 88,
      k3Score: 87,
      k4Score: 87,
      careLevel: 1,
    },
    // s-002 Stanisław Nowak — current = worst state of the three (level 3, declining)
    {
      id: "survey-s-002",
      k1Score: 54,
      k2Score: 57,
      k3Score: 53,
      k4Score: 57,
      careLevel: 3,
    },
    // s-003 Maria Wiśniewska — current = partial recovery (level 4)
    {
      id: "survey-s-003",
      k1Score: 42,
      k2Score: 41,
      k3Score: 37,
      k4Score: 43,
      careLevel: 4,
    },
  ];
  for (const fix of firstThreeFixes) {
    await prisma.survey.updateMany({
      where: { id: fix.id },
      data: {
        k1Score: fix.k1Score,
        k2Score: fix.k2Score,
        k3Score: fix.k3Score,
        k4Score: fix.k4Score,
        careLevel: fix.careLevel,
      },
    });
  }

  // ── Extra historical surveys for first 3 seniors (3 surveys each) ──────────
  //
  //  s-001 Janina Kowalska — POPRAWA (rehabilitacja + wsparcie rodziny)
  //    -300 dni: poziom 4 (duże problemy)
  //    -150 dni: poziom 2 (wyraźna poprawa)
  //    ~dziś:    poziom 1 (samodzielność) ← istniejąca ankieta poprawiona wyżej
  //
  //  s-002 Stanisław Nowak — STOPNIOWE POGORSZENIE (wiek + choroby)
  //    -330 dni: poziom 1 (dobry stan)
  //    -165 dni: poziom 2 (lekkie pogorszenie)
  //    ~dziś:    poziom 3 (wyraźne pogorszenie) ← istniejąca ankieta poprawiona wyżej
  //
  //  s-003 Maria Wiśniewska — CHWILOWE POGORSZENIE, potem powrót
  //    -270 dni: poziom 3 (umiarkowany)
  //    -120 dni: poziom 5 (kryzys – nowy incydent)
  //    ~dziś:    poziom 4 (częściowy powrót) ← istniejąca ankieta poprawiona wyżej

  type TrendSurveyData = {
    id: string;
    seniorId: string;
    k1Score: number;
    k2Score: number;
    k3Score: number;
    k4Score: number;
    careLevel: number;
    daysAgo: number;
  };

  const historicalSurveys: TrendSurveyData[] = [
    // ── s-001 Janina ──────────────────────────────────────────────────────────
    {
      id: "survey-s-001-h1",
      seniorId: "s-001",
      k1Score: 42,
      k2Score: 41,
      k3Score: 37,
      k4Score: 43,
      careLevel: 4,
      daysAgo: 300,
    },
    {
      id: "survey-s-001-h2",
      seniorId: "s-001",
      k1Score: 71,
      k2Score: 73,
      k3Score: 70,
      k4Score: 73,
      careLevel: 2,
      daysAgo: 150,
    },
    // ── s-002 Stanisław ───────────────────────────────────────────────────────
    {
      id: "survey-s-002-h1",
      seniorId: "s-002",
      k1Score: 88,
      k2Score: 88,
      k3Score: 87,
      k4Score: 87,
      careLevel: 1,
      daysAgo: 330,
    },
    {
      id: "survey-s-002-h2",
      seniorId: "s-002",
      k1Score: 71,
      k2Score: 73,
      k3Score: 70,
      k4Score: 73,
      careLevel: 2,
      daysAgo: 165,
    },
    // ── s-003 Maria ───────────────────────────────────────────────────────────
    {
      id: "survey-s-003-h1",
      seniorId: "s-003",
      k1Score: 54,
      k2Score: 57,
      k3Score: 53,
      k4Score: 57,
      careLevel: 3,
      daysAgo: 270,
    },
    {
      id: "survey-s-003-h2",
      seniorId: "s-003",
      k1Score: 29,
      k2Score: 25,
      k3Score: 23,
      k4Score: 30,
      careLevel: 5,
      daysAgo: 120,
    },
  ];

  let histCreated = 0;
  for (const hs of historicalSurveys) {
    const hsDate = new Date();
    hsDate.setDate(hsDate.getDate() - hs.daysAgo);

    await prisma.survey.upsert({
      where: { id: hs.id },
      update: {
        k1Score: hs.k1Score,
        k2Score: hs.k2Score,
        k3Score: hs.k3Score,
        k4Score: hs.k4Score,
        careLevel: hs.careLevel,
      },
      create: {
        id: hs.id,
        organizationId: org.id,
        templateId: template.id,
        seniorId: hs.seniorId,
        filledById: admin.id,
        status: "COMPLETED",
        careLevel: hs.careLevel,
        k1Score: hs.k1Score,
        k2Score: hs.k2Score,
        k3Score: hs.k3Score,
        k4Score: hs.k4Score,
        completedAt: hsDate,
        createdAt: hsDate,
      },
    });

    // Alert for level 5 survey (s-003-h2)
    if (hs.careLevel >= 5) {
      const hsAlertId = `alert-${hs.id}`;
      const hsDate2 = new Date();
      hsDate2.setDate(hsDate2.getDate() - hs.daysAgo);
      await prisma.alert.upsert({
        where: { id: hsAlertId },
        update: {},
        create: {
          id: hsAlertId,
          organizationId: org.id,
          surveyId: hs.id,
          careLevel: hs.careLevel,
          status: "IN_PROGRESS",
          createdAt: hsDate2,
        },
      });
    }

    histCreated++;
  }
  console.log(`Historical trend surveys: ${histCreated}`);

  console.log("Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
